[toolchain]
moc = "0.16.0"

[dependencies]
base = "0.16.0"
matchers = "https://github.com/kritzcreek/motoko-matchers#3dac8a071b69e4e651b25a7d9683fe831eb7cffd@3dac8a071b69e4e651b25a7d9683fe831eb7cffd"
icrc1 = "0.0.2"
ledger-types = "1.0.0"
"principal.mo" = "https://github.com/aviate-labs/principal.mo#master@c65c1da072cdc8066352ad29b56c39cde2af2a0b"
motoko-hash-map = "https://github.com/ZhenyaUsenko/motoko-hash-map#master@94d509f97d70ac03828eee3064d939a3259eab78"
map = "9.0.1"
prng = "0.0.6"
fuzz = "1.0.0"
xtended-text = "0.2.5"
vector = "0.4.3"
xtended-numbers = "0.2.1"
icrc3-mo = "0.3.5"
cert = "https://github.com/nomeata/ic-certification#v0.1.3@c403ffec0a60f658a1009976c785aa567ff0da77"
stable-rbtree = "1.0.0"
stable-buffer = "1.0.1"
stableheapbtreemap = "1.5.0"
